### ISSUE TITLE
重启完没有效果.. 

### ISSUE THREAD

**Issue by gqbre** [GhostFlying/LocationReportEnablerXposed#1]
RT.
重启完毕后，执行下面的代码并没有变为预设的值
getprop gsm.sim.operator.alpha
getprop gsm.sim.operator.iso-country
getprop gsm.sim.operator.numeric

下面是Xposed 的日志
[xposed_error_20170310_154032.log.txt](https://github.com/GhostFlying/LocationReportEnablerXposed/files/833255/xposed_error_20170310_154032.log.txt)

**Comment by GhostFlying** [comment]
xposed 并不会修改对应的属性值，仅针对特定 App hook.

**Comment by gqbre** [comment]
原来是这样，Runtastic PRO 系列软件现在也需要检测上面的三个值来决定是否允许登录。是否考虑增加可选 App hook 列表？或者是全局修改这三个属性值的选项？

**Comment by GhostFlying** [comment]
如果需要全局修改，直接使用 root 版本即可，列表的话可能有点超出本 App 的设计目的，我后续再考虑下

**Comment by gqbre** [comment]
ROOT版缺少 getprop gsm.sim.operator.alpha 这个属性的设置呢

**Comment by GhostFlying** [comment]
这东西还需要运营商名字，那倒是略猎奇。。我有空看下吧

**Comment by gqbre** [comment]
感谢~~
