### ISSUE TITLE
能否支持一下Google Translate中的即时翻译？

### ISSUE THREAD

**Issue by RuioWolf** [GhostFlying/LocationReportEnablerXposed#5]
![screenshot_20180127-033925](https://user-images.githubusercontent.com/15277799/35457673-b3b81b7c-0314-11e8-993c-b61908fb3cbe.png)
像这样，估计是因为在国内所以使用过程中有这个提示，不知道能否添加这个的支持，我用的Xposed版，Android 8.1

**Comment by GhostFlying** [comment]
我这里好像没这个入口？描述下怎么进？

**Comment by RuioWolf** [comment]
![screenshot_20180127-103703](https://user-images.githubusercontent.com/15277799/35467806-6fbc1dd0-034e-11e8-9f64-238505f8fe70.png)
文本框左下角这个像相机一样的logo就是

**Comment by GhostFlying** [comment]
我这里进去后是没有即时翻译的，只有拍照

**Comment by RuioWolf** [comment]
大概是我表述错了，就是拍照和从相册选取照片的时候出现的这个提示，即时翻译似乎只要下载了离线翻译包就能用
